### ISSUE TITLE
Compile Sigar to ARM (Raspberry pi)

### ISSUE THREAD

**Issue by jcbfonseca** [hyperic/sigar#101]
Hi all,

Does anyone know what i need to change to compile Sigar to arm to execute in a Raspberry Pi? 
Is it a big or low effort?

Thanks,
Jorge.

**Comment by spyhunter99** [comment]
I did it once, painless

**Comment by jcbfonseca** [comment]
Good spyhunter99.
Did you compile it directly in a rasp or use a arm toolchain in a linux machine?

Could you provide some tips which files i need to change?

Jorge.

**Comment by AlexYaruki** [comment]
Easiest way would be compilation using cmake on Raspberry. You would not need to change anything.

**Comment by spyhunter99** [comment]
I compiled on the pi, I don't recall changing anything

**Comment by jcbfonseca** [comment]
I compiled with:
 - autogen.sh
 - ./configure
 - make

with no errors. But when i execute it, i always got java.lang.UnsatisfiedLinkError.
Is there a doc describe the steps to compile? Which steps i do need to add?

(i use the ./libs/libsigar.so file)

Thanks.

**Comment by AlexYaruki** [comment]
Is library added to java.library.path ?

**Comment by jcbfonseca** [comment]
Yes.

The same happened in Ubuntu. 
1- I downloaded the binaries from github (execution is ok).
2- I compiled and replace the the amd64-linux.so  by generated libsigar.so (in ubuntu).
3- I got the UnsatisfiedLinkError error too.

Can be a wrong compilation?

**Comment by AlexYaruki** [comment]
Binaries from github ? You mean JAR file ?

**Comment by jcbfonseca** [comment]
Sorry - sourceforge (not github).

**Comment by jcbfonseca** [comment]
Do I need to pass some parameter in the "configure" step?

**Comment by AlexYaruki** [comment]
What is the complete exception message ?

**Comment by jcbfonseca** [comment]
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Sigar.getNativeVersion()Ljava/lang/String;
	at org.hyperic.sigar.Sigar.getNativeVersion(Native Method)
	at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:101)
	at org.hyperic.sigar.cmd.Shell.<init>(Shell.java:50)
	at org.hyperic.sigar.cmd.SigarCommandBase.<init>(SigarCommandBase.java:75)
	at nodestats.CpuInfo.<init>(CpuInfo.java:40)
	at nodestats.CpuInfo.main(CpuInfo.java:104)

**Comment by AlexYaruki** [comment]
As I suspected, core sources do not contain JNI code for Java. So you are trying to use core library ( C) with Java library that requires JNI exported functions. I think what you should do instead is to build directly from java bindings subdirectory with Apache Ant.

**Comment by jcbfonseca** [comment]
When i try to generated the jar file, i got this message:

 [cc] Starting link
       [cc] ../sigar_version_autoconf.o: In function `sigar_version_get':
       [cc] sigar_version_autoconf.c:(.text+0x0): multiple definition of `sigar_version_get'
       [cc] ../sigar_version.o:sigar_version.c:(.text+0x0): first defined here
       [cc] ../sigar_getline.o: In function `sigar_getline_histadd':
       [cc] sigar_getline.c:(.text+0x1db8): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
       [cc] collect2: error: ld returned 1 exit status

**Comment by jcbfonseca** [comment]
i saw in the build.xml file that sigar_version.c is copied from 'c core source'.
Any suggestion?

**Comment by AlexYaruki** [comment]
Could you insert complete log from building ?

**Comment by jcbfonseca** [comment]
[build.txt](https://github.com/hyperic/sigar/files/768738/build.txt)

DO you have any idea?

**Comment by AlexYaruki** [comment]
I will look in to this problem on Monday when I will setup my Raspberry

**Comment by AlexYaruki** [comment]
Which Raspberry Pi model and OS ?

**Comment by jcbfonseca** [comment]
I got this error when compiled in:

 - Ubuntu 16.04
and
 - Rasp 3 Model B - version 8.0 (Jessie)

Thanks for help.

**Comment by jcbfonseca** [comment]
Alex,

I compiled with success adding a exclude property in jni-build.xml:
      # C Sources #
      < fileset dir="${jni.source.dir}" >
         < patternset refid="jni.source.files" / >
         < exclude name="src/sigar_version_autoconf.c"/>
      </ fileset>

This new JAR file works fine with .so from sourceforge.
But again: i got UnsatisfiedLinkError with .so generated by compilation process (Ubuntu or RaspberryPi).

Any idea?

**Comment by jcbfonseca** [comment]
Aex and All,

Issue solved.
Once the jni-build.xml was fixed, i still use the ./src/libsigar.so file. When i change the .so file to ./bindings/java/sigar-bin/lib/libsigar.so the execution works fine. (as told by you Alex).

Thanks for the support.

By the way: i suggest you to verify the problem related to jni-build.xml.

Thanks again.

**Comment by AlexYaruki** [comment]
You were using GUI version of Raspbian or headless (bash-only) ?
