### ISSUE TITLE
JVM crashes occassionally with access violation when using Sigar.getProcMem with disabled Windows performance counters

### ISSUE THREAD

**Issue by jgoeres** [hyperic/sigar#77]
We are using Sigar 1.6.4 to monitor, among other things, CPU and memory usage of the components of our software. Sigar itself is used from within our "Agent" component, which is responsible for controlling the lifecycle and monitoring all components. 
Recently, we are getting more reports that the agent crashes with an access violation (hs_err_pid file written to disk). 

Usually, the stack trace in the hs_err_pid file indicates that it is directly related to the use of getProcMem():

`Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.hyperic.sigar.ProcMem.gather(Lorg/hyperic/sigar/Sigar;J)V+0
j  org.hyperic.sigar.ProcMem.fetch(Lorg/hyperic/sigar/Sigar;J)Lorg/hyperic/sigar/ProcMem;+11
j  org.hyperic.sigar.Sigar.getProcMem(J)Lorg/hyperic/sigar/ProcMem;+2
[...]`

Sometimes, the issue also happens when the Sigar instance that we used for getProcMem is closed by our code:

`Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.hyperic.sigar.Sigar.nativeClose()I+0
j  org.hyperic.sigar.Sigar.close()V+8
[...]`

I attached a sample hs_err_pid (which I had to obfuscate a bit, replacing package, product and servernames).

What we noticed first was that on more and more of our machines, the memory measurement would suddenly no longer work, where it had worked fine before. 
When I first debugged this, I noticed that a SigarException was being thrown by getProcMem():

`org.hyperic.sigar.SigarException: No Process counters defined (disabled?)
    at org.hyperic.sigar.ProcMem.gather(Native Method)
    at org.hyperic.sigar.ProcMem.fetch(ProcMem.java:30)
    at org.hyperic.sigar.Sigar.getProcMem(Sigar.java:445)`

So quite obviously, it is related to the Windows performance counters having been disabled on these machines. Checking the registry confirmed this:

`[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\PerfProc\Performance]
"Disable Performance Counters"=dword:00000001`

If we set this setting to 0 and restart the "WMI Performance Adapter" service, measurements work again and we also have never seen the access violation happening with enabled perf counters.

Currently, we could live with memory measurements not being available on machines with disabled performance counters, but we have no good way of figuring this out ourselves from within the agent. 
If we would simply always get the above mentioned exception, we would be OK (as we have a functionality to disable measurements if they fail repeatedly) - it is the occasional access violation that is really spoiling it. 
Still, I would hope that there is another way to get a process's memory usage without resorting to the performance counters.

[hs_err_pid27764.log.txt](https://github.com/hyperic/sigar/files/230051/hs_err_pid27764.log.txt)

**Comment by jgoeres** [comment]
We are now also getting this from time to time when using getNetConnectionList():

```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j org.hyperic.sigar.Sigar.getNetConnectionList(I)[Lorg/hyperic/sigar/NetConnection;+0
j a.b.c.agent.monitoring.MachineMonitor.getNetstatInfo([La/b/c/common/monitoring/NetstatInfo$NetstatFlags;)La/b/c/common/monitoring/NetstatInfo;+21
j a.b.c.agent.monitoring.MachineMonitor.getNetstatInfo([Ljava/lang/String;)La/b/c/common/monitoring/NetstatInfo;+100
j a.b.c.agent.monitoring.NetworkConnectionMonitor.checkNetworkConnections()V+8
j a.b.c.agent.monitoring.NetworkConnectionMonitor.run()V+20
v ~StubRoutines::call_stub 
```

**Comment by vamekhgoiati** [comment]
We are getting it on getProcList()

` 
Stack: [0x0000000092590000,0x0000000092690000],  sp=0x000000009268d250,  free space=1012k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [sigar-amd64-winnt.dll+0x14ed4]
C  [sigar-amd64-winnt.dll+0x23b4c]
C  0x0000000001955e34

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.hyperic.sigar.Sigar.getProcList()[J+0
j  a.b.c.killOfficeProcess()V+9
j  a.b.c.start()V+1
v  ~StubRoutines::call_stub
`

**Comment by jgoeres** [comment]
Meanwhile, we built a workaround: we do one initial attempt at memory usage measurement, if this fails, we disable it globally. Problem is: sometimes this initial attempt works, so we keep everything enabled. But then, when we later close the Sigar instance, it sometimes crashes with an access violation:

Stack: [0x0000000068050000,0x0000000068150000],  sp=0x000000006814e6e0,  free space=1017k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [ntdll.dll+0x4e330]
C  [kernel32.dll+0x21a0a]
C  [sigar-amd64-winnt.dll+0x32fcc]
C  [sigar-amd64-winnt.dll+0x56d1]
C  [sigar-amd64-winnt.dll+0xd6d9]
C  [sigar-amd64-winnt.dll+0x15606]
C  0x0000000001857f34

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.hyperic.sigar.Sigar.nativeClose()I+0
j  org.hyperic.sigar.Sigar.close()V+8
j  a.b.c.plugin.base.health.X.close()V+4
j  a.b.c.plugin.base.health.Y.close()V+47
j  a.b.c.plugin.base.Z.stopAndDeinitializeHealthMonitoring()V+29
j  a.b.c.plugin.base.Z.beforeStop()V+1
j  a.b.c.lifecycle.W$17.run()V+4
J 9203 C1 java.lang.Thread.run()V (17 bytes) @ 0x00000000024a377c [0x00000000024a3640+0x13c]
v  ~StubRoutines::call_stub

**Comment by maurits150** [comment]
I can confirm the same is happening with ProcFd.


Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.hyperic.sigar.ProcFd.gather(Lorg/hyperic/sigar/Sigar;J)V+0
j  org.hyperic.sigar.ProcFd.fetch(Lorg/hyperic/sigar/Sigar;J)Lorg/hyperic/sigar/ProcFd;+11
j  org.hyperic.sigar.Sigar.getProcFd(J)Lorg/hyperic/sigar/ProcFd;+2
J 4865 C2 com.projectname.daemon.executor.server.executor.process.SystemProcess.calculateProcessor()V (178 bytes) @ 0x000000000340b240 [0x000000000340b200+0x40]
j  com.projectname.daemon.executor.server.executor.process.SystemProcess.run()V+8
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub

Full crash dump: https://maurits.tv/data/file/January%202017/2017-01-23_00-44-18_wCo7tJocBk.txt

As you can see it only happened after 5 minutes. CPU usage was polling every second. The JVM was doing some heavy IO/compression work during the crash.

**Comment by spyhunter99** [comment]
@jgoeres how in the world did you find that registry key? You have probably saved several hours if not days of troubleshooting. Thank you! my library with sigar was working fine for literally years for me. Yesterday I shut down my computer and when it came back up sigar stopped working. I'm not sure how or why that registry key changed but i'd sure like to know.

**Comment by jgoeres** [comment]
@spyhunter99 I guess I had some good Google foo that day.
Anyway, maybe I should share my perspective on the future of Sigar in our product:
We recently migrated our software to Java 9. When working on my component (the one making use of Sigar) on my primary dev machine (running Win 7), everything seemed to work fine initially after switching to a JRE9, of course with the various workarounds described above in place. When we did a test run on one of our test servers running Win2016 Server, however, Sigar would always crash the JVM virtually immediately, pretty much regardless of of what method you called. Same on my second Dev machine running Win10. On Windows 2012 Servers it was working fine.
Alas, we do not have the resources to start fixing Sigar ourselves (we are a Java shop after all... ;-)), so I grudgingly went ahead and removed Sigar completely, at the loss of a lot of our monitoring functionality.
Fortunately, I was able to replace one essential functionality we used Sigar for with the new Java Process API that is part of Java 9.

**Comment by spyhunter99** [comment]
Interesting, i've been playing around with oshi recently. My only complaint is that it's rather slow to get process info on windows due to wmi queries.
